### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by olechnwin** [AppliedBioinformatics/runBNG#28]
Hello,

I have an error when running the following command:
```
~/opt/runBNG/runBNG denovo \
		-t      ~/opt/bionano/tools/pipeline/Solve3.6.1_11162020/RefAligner/1.0 \
		-s      ~/opt/bionano/tools/pipeline/Solve3.6.1_11162020 \
		-b      ~/Data/A673_bionano/EwingSarcoma_November2019/EwingsSarcoma_Solve3.4_pipeline_results/output/all.bnx \
		-M      yes \
		-a      9 \
		-T      $((SLURM_CPUS_PER_TASK-2)) \
		-j      2 \
		-z      3137 \
		-m      3 \
		-r      ~/Data/A673_bionano/runBNG_rslt/hg19_DLE1_20kb_5labels.cmap \
		-o      ~/Data/A673_bionano/runBNG_rslt
```
These are the last warning/error messages:
```
Warning summary:
	983 warning(s)

WARNING: missing cnv file: /home/Data/A673_bionano/runBNG_rslt/contigs/alignmolvref/copynumber/cnv_calls_exp.txt


Starting smap2vcf script:
python /home/opt/bionano/tools/pipeline/Solve3.6.1_11162020/Pipeline/11162020/Analysis/vcf_converter/bionano_vcf_converter.py -s /home/Data/A673_bionano/runBNG_rslt/contigs/exp_refineFinal1_sv/merged_smaps/exp_refineFinal1_merged_filter_inversions.smap -x /home/Data/A673_bionano/runBNG_rslt/contigs/exp_refineFinal1_sv/merged_smaps/exp_refineFinal1_merged.xmap -r /home/Data/A673_bionano/runBNG_rslt/contigs/exp_refineFinal1_sv/merged_smaps/exp_refineFinal1_merged_r.cmap -o /home/Data/A673_bionano/runBNG_rslt/contigs/exp_refineFinal1_sv/merged_smaps/exp_refineFinal1_merged_filter_inversions -a hg19_DLE1_20kb_5labels.cmap -b False -m 0

Traceback (most recent call last):
  File "/home/opt/bionano/tools/pipeline/Solve3.6.1_11162020/Pipeline/1.0/pipelineCL.py", line 52, in <module>
    dnpipeline.run(conf)
  File "/home/opt/bionano/tools/pipeline/Solve3.6.1_11162020/Pipeline/11162020/Pipeline.py", line 2129, in run
    self.finalizePipeline(conf, ers)
  File "/home/opt/bionano/tools/pipeline/Solve3.6.1_11162020/Pipeline/11162020/Pipeline.py", line 2895, in finalizePipeline
    self.smap2vcf(conf)
  File "/home/opt/bionano/tools/pipeline/Solve3.6.1_11162020/Pipeline/11162020/Pipeline.py", line 2885, in smap2vcf
    log = os.path.join(conf.clusterLogDir, stageName + ".log")
  File "/usr/lib64/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
Python Exception : 'NoneType' object has no attribute 'endswith'
Exception stack trace:
```
I am attaching the full log for more info.
[runbng_denovo_391392.txt](https://github.com/AppliedBioinformatics/runBNG/files/6313173/runbng_denovo_391392.txt)

Thank you again for your help.

**Comment by yuxuanyuan** [comment]
Hi @olechnwin, 

I didn't test the CNV calling function in this. Maybe i need to disable it or set an option in the next update. 

From the log file, it seems this is a warning and you can still get your denovo assembly file at ``/home/Data/A673_bionano/runBNG_rslt/contigs/exp_refineFinal1/EXP_REFINEFINAL1.cmap``

**Comment by olechnwin** [comment]
Hi @yuxuanyuan.

Thanks for your reply. Ahh...so it's doing CNV as well. 
I didn't realize I already have my denovo assembly. Thanks!
