### ISSUE TITLE
Missing module of pybionano.smapdata

### ISSUE THREAD

**Issue by liangwx332** [AppliedBioinformatics/runBNG#35]
Hello,

I run runBNG for your  example and all dependence has been solved. But I did not get right result, the error as following.
Would you give me some suggestions?

Lwx

========================= ============Code===================================
runBNG denovo -t /share/home/biosoft/tools/pipeline/Solve3.7_10192021_74_1/RefAligner/12432.12463rel/ -s /share/home/biosoft/tools/pipeline/Solve3.7_10192021_74_1/  -b Molecules.bnx -T 5 -l 120 -m 8 -j 30 -z 100 -o test

======================================Error===================================
========================================== De novo assembly starts =============================================
## The output directory is: test

Traceback (most recent call last):
  File "/share/home/biosoft/tools/pipeline/Solve3.7_10192021_74_1/Pipeline/1.0/pipelineCL.py", line 11, in <module>
    import Pipeline
  File "/share/home/biosoft/tools/pipeline/Solve3.7_10192021_74_1/Pipeline/10192021/Pipeline.py", line 31, in <module>
    import reports
  File "/share/home/biosoft/tools/pipeline/Solve3.7_10192021_74_1/Pipeline/10192021/reports.py", line 8, in <module>
    from varcluster import VariantClustering
  File "/share/home/biosoft/tools/pipeline/Solve3.7_10192021_74_1/Pipeline/10192021/varcluster.py", line 7, in <module>
    from pybionano.smapdata import SmapData, SmapFilter
ModuleNotFoundError: No module named 'pybionano.smapdata'

**Comment by liangwx332** [comment]
I try to search the python module of pybionano.smapdata ,bur without any result.
I do not know why does runBNG miss the module?

**Comment by yuxuanyuan** [comment]
Sorry for the late reply. You may download [Bionanao Solve3.5.1](https://figshare.com/articles/software/Solve3_5_1_01142020_tar_gz/20295249) and try again.
