### ISSUE TITLE
OSError: [Errno 2] No such file or directory when running runBNG denovo on the example data

### ISSUE THREAD

**Issue by 0xaf1f** [AppliedBioinformatics/runBNG#38]
I've set runBNG up with the older bionano solve version 3.5 as you [suggested](https://github.com/AppliedBioinformatics/runBNG/issues/37#issuecomment-1203485174) in #37 (I might be able to help to some extent with updating for python 3/ bionano 3.7 compatibility), but I get this error when trying to de novo assemble the test data.

## dependency/system info

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
$
$ python --version
Python 2.7.15
$ python -c "import dateutil" && echo ok
ok
$ python -c "import lxml" && echo ok
ok
$ perl -version

This is perl 5, version 14, subversion 4 (v5.14.4) built for x86_64-linux-thread-multi
(with 1 registered patch, see perl -V for more detail)

Copyright 1987-2013, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

$ R --version
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 
```

## error

```
runBNG denovo -t /opt/Solve3.5.1_01142020/RefAligner/1.0 -s /opt/Solve3.5.1_01142020  -b runBNG/Examples/Molecules.bnx -T 1  -o $PWD/output -j 1  -z 5 -P irys -e no
========================================== De novo assembly starts =============================================
## Start date: Mon Sep  5 22:30:28 UTC 2022
## The data generation platform is: irys
## The bnx file is: /home/user/runBNG/Examples/Molecules.bnx
## The minimum molecule length is (Kb): 150
## The minimum label on a molecule is: 8
## Maximum backbone intensity is: 0.6
## The path to Bionano Solve folder is: /opt/Solve3.5.1_01142020
## The path to Bionano RefAligner folder is: /opt/Solve3.5.1_01142020/RefAligner/1.0
## The number of threads is: 1
## Large jobs maximum memory (GB) is: 128
## Small jobs maximum memory (GB) is: 8
## The number of threads for each subjob is: 1
## The number of iterations is: 5
## False Positive Density (/100Kb) [FP]: 2.0
## False Negative Rate (%/100) [FN]: 0.10
## ScalingSD (Kb^1/2) [sd]: 0.0
## SiteSD (Kb) [sf]: 0.15
## RelativeSD [sr]: 0.03
## The genome size (Mb) is: 5
## The xml file is: /opt/Solve3.5.1_01142020/RefAligner/1.0/optArguments_nonhaplotype_irys.xml
## The output directory is: /home/user/output

  Prerun Tests:
	0 ERRORS
	3 WARNINGS

Disabling autoNoise during rough Assembly

  WARNING: rough assembly argument > 0 (0.500000) but no reference supplied: running rough assembly with no reference
  WARNING: Disabling SV detection (-V, default ON) because no reference supplied, or invalid.
  WARNING: Disabling alignment of molecules vs reference (-m, default ON) because no reference supplied, or invalid.

Tools Version: N/A
Solve Version: N/A
Pipeline Version: 10322
RefAligner Version: 10436

Assembly ID: 748

  Pipeline start time: Mon Sep  5 22:30:28 2022

checkScanScaling: autoNoise= False
Not performing autoNoise (see -y): setting doScanScale = False, hence not using _rescaled.bnx for BNX splits
Executing stage number 1 : AutoNoise + SplitBNX

Molecule Stats (/home/user/output/all.bnx):
Total number of molecules:   7326
Total length (Mbp)       :   1595.095
Average length (kbp)     :    217.731
Molecule N50 (kbp)       :    236.401
Label density (/100kb)   :     11.015

Sorting /home/user/output/all.bnx into /home/user/output/all_sorted
 Starting Multi-Threaded Process: SortBNX
  Running 1 jobs with 1 threads, sleepTime=0.02
Python Exception : [Errno 2] No such file or directory
<type 'exceptions.Exception'>
exception stack trace:
Traceback (most recent call last):
  File "/opt/Solve3.5.1_01142020/Pipeline/1.0/pipelineCL.py", line 54, in <module>
    dnpipeline.run(varsP)
  File "/opt/Solve3.5.1_01142020/Pipeline/12162019/Pipeline.py", line 1853, in run
    if self.constructData(varsP): # auto Noise, splitBNX, returns 0 on successful completion, 1 on failure or exit after sample char
  File "/opt/Solve3.5.1_01142020/Pipeline/12162019/Pipeline.py", line 1949, in constructData
    pm.sortBNX(varsP) #raise RuntimeError if job fails
  File "/opt/Solve3.5.1_01142020/Pipeline/12162019/PairwiseModule.py", line 169, in __init__
    self.varsP.runJobs(self, "SortBNX")
  File "/opt/Solve3.5.1_01142020/Pipeline/12162019/Pipeline.py", line 1617, in runJobs
    module.runJobs()
  File "/opt/Solve3.5.1_01142020/Pipeline/12162019/PairwiseModule.py", line 182, in runJobs
    self.multiThreadRunJobs(self.varsP.nThreads)
  File "/opt/Solve3.5.1_01142020/Pipeline/12162019/Multithreading.py", line 304, in multiThreadRunJobs
    sJob.startJob(cSession=cSession, clusterArgs=clustarg)
  File "/opt/Solve3.5.1_01142020/Pipeline/12162019/Multithreading.py", line 713, in startJob
    super(singleJob, self).__init__(jobArgs, stdout=stdout, stderr=stderr)
  File "/opt/conda/envs/local/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/opt/conda/envs/local/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

## End date: Mon Sep  5 22:30:28 UTC 2022
===============================================================================================================
```

**Comment by bwfarm2** [comment]
Hi, I have encountered the same issue.  Did you find a resolution to this?

**Comment by bwfarm2** [comment]
I wanted to add, just in case anyone else encounters this error:

I had created the base environment as a Singularity container.  The error message was due to not having "time" installed,  the command that "not found" was:
`['/usr/bin/time', '-f', '%U\t%S\t%E\t%P\t%M', '/share/apps/amd/runBNG-BIONANO/Solve3.5.1_01142020/RefAligner/1.0/RefAligner', ... ]`
